### ISSUE TITLE
Current TODO

### ISSUE THREAD

**Issue by ifavila** [Maz-Bil/ASU-Share-My-Schedule#1]
- [ ] Figure out how to make Chrome extensions
- [ ] Figure out adding email functionality
- [ ] Figure out adding formatting and auto appending HTML info to csv/pdf/docx files
